version: '3.8'
services:
  app:
    image: pwa
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /app/node_modules
      - /app/.next
    ports:
      - ${APP_EXPOSED_PORT:-0}:3000
