name: Deploy to production

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: vm02
        port: 22
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        proxy_host: 13.37.197.59
        proxy_port: 22
        proxy_username: root
        proxy_key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /srv/web-app
          git reset --hard HEAD^
          git pull
          docker compose build
          docker compose down
          docker compose up -d
