name: Rollback Last Production Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    uses: gibical/infra/.github/workflows/eks-rollback.yaml@main
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.PROD_AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
    with:
      name:  ${{ github.event.repository.name }}
      cluster: ${{ vars.PROD_CLUSTER }}
      region: ${{ vars.PROD_REGION }}
      namespace: ${{ vars.NAMESPACE }}
